[project]
name = "ocotillopmf"
version = "0.1.0"
description = "This is a python library to generate synthetic clusters of protostars in steady state"
readme = "README.md"
authors = [
    { name = "Brandt Gaches", email = "brandt.gaches@uni-due.de" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
    "scipy>=1.17.1",
]
license = "BSD-3-Clause"

[project.optional-dependencies]
examples = ["matplotlib", "seaborn", "jupyter"]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"
