[project]
name = "ocotillopmf"
version = "0.1.0"
description = "This is a python library to generate synthetic clusters of protostars in steady state"
readme = "README.md"
authors = [
    { name = "Brandt Gaches", email = "brandt.gaches@uni-due.de" }
]
requires-python = ">=3.11"
dependencies = [
    "fyeldgenerator>=0.1.7",
    "numpy>=2.4.6",
    "scipy>=1.17.1",
]
license = "BSD-3-Clause"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Repository = "https://github.com/AstroBrandt/OcotilloPMF"
Issues = "https://github.com/AstroBrandt/OcotilloPMF/issues"

[project.optional-dependencies]
examples = ["matplotlib", "seaborn", "jupyterlab"]

[build-system]
requires = ["uv_build>=0.8.22,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
